trigger:
  branches:
    include:
      - vnext

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: UseGitVersion@5
    displayName: "Git Version"
    inputs:
      versionSpec: "5.0.0"
      useConfigFile: true
      configFilePath: "GitVersion.yml"
  - task: Yarn@3
    displayName: "Update package.json version"
    inputs:
      arguments: "version --new-version $(Build.BuildNumber) --no-git-tag-version"
  - task: Yarn@3
    displayName: "Install"
    inputs:
      ProjectDirectory: "."
  - task: Yarn@3
    displayName: "Build"
    inputs:
      arguments: "build"
  - task: Yarn@3
    condition:
    inputs:
      arguments: "pack --filename $(Build.StagingDirectory)/package.tgz"
  # - task: PublishBuildArtifacts@1
  #   displayName: "Publish Artifact: tgz"
  #   inputs:
  #     PathtoPublish: "$(Build.StagingDirectory)/package.tgz"
  #     ArtifactName: npm
  - task: Npm@1
    inputs:
      command: 'publish'
      publishRegistry: 'useFeed'
      publishFeed: 'da7703d4-fb22-4933-b869-83f4264b7b84/e1336e71-3540-4a0c-830c-639112685b07'
