trigger:  
  branches:
    include:
      - vnext

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: "Yarn"
    inputs:
      ProjectDirectory: "."