trigger:  
  branches:
    include:
      - vnext

pool:
  vmImage: "ubuntu-18.04"

steps:
- task: Yarn@3
  displayName: "Install"
  inputs:
    ProjectDirectory: "."
- task: Yarn@3
  displayName: "Build"
  inputs:
    arguments: 'build'
- task: Yarn@3
  displayName: "Pack"
  inputs:
    arguments: 'pack'