trigger:  
  branches:
    include:
      - vnext

pool:
  vmImage: "ubuntu-18.04"

steps:
- task: UseGitVersion@5
  displayName: "Version"
  inputs:
    versionSpec: '5.0.0'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
- task: Yarn@3
  displayName: "Install"
  inputs:
    ProjectDirectory: "."
- task: Yarn@3
  displayName: "Build"
  inputs:
    arguments: 'build'
- task: Yarn@3
  condition: 
  inputs:
    arguments: 'publish --new-version $(Build.BuildNumber)'
    customRegistry: 'useFeed'
    customFeed: 'e1336e71-3540-4a0c-830c-639112685b07'
